version: '3'

networks:
  local-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.60.0.0/16

services:

  app:
    restart: always
    build:
      context: .
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      - /node_modules
    environment:
      NODE_ENV: development
      DB_TYPE: mongo
      DB_HOST: mongodb://10.60.0.20
      DB_PORT: 27017
      DB_NAME: candy_db
      BASIC_ADMIN_TOKEN: "uM4kWQqF1F4r5Jszkq%bqfe"
      MORGAN_LOG: dev
    command: npm run dev
    networks:
      local-net:
        ipv4_address: 10.60.0.10
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      local-net:
        ipv4_address: 10.60.0.20

volumes:
  mongodb_data: