version: '3'

networks:
  local-net:

services:

  rest-api:
    restart: always
    build:
      context: .
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      - /node_modules
    environment:
      NODE_ENV: development
      DB_TYPE: mongo
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: candy_db
      BASIC_ADMIN_TOKEN: "uM4kWQqF1F4r5Jszkq%bqfe"
      MORGAN_LOG: dev
    command: npm run dev
    networks:
      - local-net
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    command: ["mongod", "--port", "27017", "--quiet", "--logpath" ,"/dev/null"]
    volumes:
      - mongodb_data:/data/db
    networks:
      - local-net

volumes:
  mongodb_data: